dist: xenial
language: python
python:
  - "3.4"
cache: 
  pip: true
install:
  - pip install -r requirements.txt
script:
  - python3 python/helloworld.py
  - python3 python/prime1000.py
  - python3 python/mandelbrot.py

after_success:
#  - codecov
