dist: xenial
language: python
python:
  - "3.6"
cache: 
  pip: true
install:
  - pip install codecov
script:
  - python esp8266/*.py
  - coverage run esp8266/prime1000.mpy

after_success:
  - codecov
